name: Open Authenticator build
on: [push, pull_request]

jobs:
  build-test:
    name: Test Build of Open Authenticator firmware
    runs-on: ubuntu-20.04
    container:
      image: espressif/idf:release-v4.2
    steps:  
      - name: Preinstall github binary
        run: |
          apt-get update
          apt-get install -y software-properties-common
          apt-get update
          add-apt-repository -y ppa:git-core/ppa
          apt-get update
          apt-get install -y git    
      - uses: actions/checkout@v2
        with: 
          submodules: 'recursive'
      - name: Testing open authenticator app
        run: |
          . $IDF_PATH/export.sh
          idf.py build
